Support for special characters on the URL + support Unity's compressed build
krsbx/SimpleHTTPServer pull request #1
Opened 2021-09-15 19:55 UTC by forestrf

Support for special characters on the URL + support Unity's compressed build

2021-09-18 15:30 UTC, krsbx commented on HttpServer.cs
> +    filename = HttpUtility.UrlDecode(filename);
we could make this one into

string filename = HttpUtility.UrlDecode(context.Request.Url.AbsolutePath);

2021-09-18 15:30 UTC, krsbx commented on HttpServer.cs
> +    }
For this part, I think we could make it into a functions, so we coudl make it to be like this

bool checkIfValid () {
try{
return ...
}catch(err){
return ...
}
}

2021-09-18 15:31 UTC, krsbx requested changes
please change the code

2021-09-18 16:57 UTC, forestrf commented
I'm sorry, I didn't want to commit so many changes at once, I thought a pull request was for a specific commit, not for a branch.
Let me do those changes, yes

2021-10-13 22:42 UTC, forestrf commented
Changes updated, simplified and the path validation is now in a separate function

2021-10-13 23:01 UTC, krsbx approved these changes
LGTM

2021-10-13 23:01 UTC, krsbx commented on HttpServer.cs
> +        {".wasm", "application/wasm"},
for this one, I think its better to split the mimeType into another class, so the HttpServer class only going to contain the code for server handling

2021-10-13 23:01 UTC, krsbx commented on HttpServer.cs
> +    filename = HttpUtility.UrlDecode(filename);
we could make this one into

string filename = HttpUtility.UrlDecode(context.Request.Url.AbsolutePath);

2021-10-13 23:01 UTC, krsbx commented on HttpServer.cs
> +    }
For this part, I think we could make it into a functions, so we coudl make it to be like this

bool checkIfValid () {
try{
return ...
}catch(err){
return ...
}
}

2021-10-13 23:02 UTC, merged

2021-10-14 01:24 UTC, forestrf commented
I wasn't able to see the comments! I don't know why, now I can see them. That gave me problems to fix the problems you pointed out, so I tried to fix them by aking the code as simple as possible and with as few changes as possible.